.github/workflows/ci.yml
- CI 파일 수정
- github actions 에 secret 저장
=> [fix] CI 수정

final_project_backend/src/main.ts
=> [fix] CI/CD 테스트용 수정 - swagger description 수정

.github/workflows/cd.yml, .github/workflows/ci.yml
=> [fix] CI/CD 파일 수정

final_project_backend/src/main.ts
=> [fix] CI/CD 테스트용

.github/workflows/cd.yml, .github/workflows/ci.yml
=> [fix] ci/cd 파일수정

.github/workflows/cd.yml, .github/workflows/ci.yml
=> [fix] CI CD 파일 수정

.github/workflows/cd.yml
=> [fix] cd 파일 수정

final_project_backend/src/auth/auth.service.ts, final_project_backend/src/user/dto/delete-user.dto.ts, final_project_backend/src/user/dto/search-user.dto.ts, final_project_backend/src/user/dto/update-user.dto.ts, final_project_backend/src/user/user.controller.ts, final_project_backend/src/user/user.service.ts
<!-- 관련있는 이슈 번호(#000)을 적어주세요.
closed #19 
내 정보 수정
내 정보 삭제 ( 회원 탈퇴 )
다른 사람 정보 조회 기능  구현완료
회원 정보를 수정할때는 
기존의 password는 꼭 입력해야하고 
나머지 이름, 새로운 비밀번호, 이미지 URL은 선택사항입니다. 
3가지 중 한가지만 선택해서 값을 넣으시면 그 한 가지만 값이 바뀔겁니다.
=> 19 feature user 수정 삭제 조회

final_project_backend/src/app.module.ts, final_project_backend/src/community/community.controller.ts, final_project_backend/src/community/community.module.ts, final_project_backend/src/community/community.service.ts, final_project_backend/src/community/dto/create-community.dto.ts, final_project_backend/src/community/dto/update-community.dto.ts, final_project_backend/src/community/entities/community.entity.ts, final_project_backend/src/community/entities/communityUser.entity.ts
=> feature-#17-community, communityUser entity

final_project_backend/package-lock.json, final_project_backend/package.json, final_project_backend/src/auth/decorators/roles.decorator.ts, final_project_backend/src/auth/guards/roles.guard.ts, final_project_backend/src/data-source.ts, final_project_backend/src/database/seeds/admin.seeder.ts, final_project_backend/src/user/entities/user.entity.ts, final_project_backend/src/user/types/user-role.type.ts, final_project_backend/src/user/user.controller.ts, final_project_backend/src/user/user.service.ts
현재 인가 기능을 위해 Guard만 구현된 상태 입니다.
'다른 사람 정보 조회' 기능에 테스트로 Admin만 가능하게 구현했습니다.
추후 삭제할 예정입니다.
그리고 seed 기능을 추가했으나 아직 오류를 해결 못한 상태입니다. 
하지만 실행하는데 문제는 없습니다. 이것도 오늘 안에 해결할 예정입니다.
=> 21 feature 관리자 기능

final_project_backend/src/community/community.module.ts
app.module 에러 발생해 서버가 내려가는 문제 발생함
임시방편으로 community.module 껍데기만 만들어 PR
Related to : #35
=> fix : community.module 모듈 생성

final_project_backend/src/community/community.controller.ts, final_project_backend/src/community/community.module.ts, final_project_backend/src/community/community.service.ts, final_project_backend/src/community/entities/community.entity.ts, final_project_backend/src/community/entities/communityUser.entity.ts, final_project_backend/src/user/entities/user.entity.ts
#17 
커뮤니티 API별 권한 Guard 이용하게 수정
=> 17 feature community

final_project_backend/package-lock.json, final_project_backend/package.json, final_project_backend/src/app.module.ts, final_project_backend/src/community/community.controller.ts, final_project_backend/src/community/community.service.ts, final_project_backend/src/community/entities/communityUser.entity.ts, final_project_backend/src/membership/entities/membership-payment.entity.ts, final_project_backend/src/membership/entities/membership.entity.ts, final_project_backend/src/membership/membership.service.ts
- 멤버십 생성 / 조회 / 연장 기능 구현완료했습니다!!
=> 멤버십 api 구현완료

final_project_backend/package-lock.json, final_project_backend/package.json, final_project_backend/src/admin/admin.module.ts, final_project_backend/src/admin/services/admin-artist.service.ts, final_project_backend/src/admin/services/admin-manager.service.ts, final_project_backend/src/auth/auth.controller.ts
=> update : 아티스트/매니저 생성 시 커뮤니티 유저에 가입되게 구현

final_project_backend/src/app.module.ts, final_project_backend/src/auth/guards/jwt-auth.guard.ts, final_project_backend/src/comment/comment.controller.ts, final_project_backend/src/comment/comment.module.ts, final_project_backend/src/comment/comment.service.ts, final_project_backend/src/community/entities/communityUser.entity.ts, final_project_backend/src/constants/message.constant.ts, final_project_backend/src/data-source.ts, final_project_backend/src/like/dto/create-like.dto.ts, final_project_backend/src/like/entities/like.entity.ts, final_project_backend/src/like/like.module.ts, final_project_backend/src/like/like.service.ts, final_project_backend/src/like/types/itemType.types.ts, final_project_backend/src/like/types/likeStatus.types.ts, final_project_backend/src/post/post.controller.ts, final_project_backend/src/post/post.module.ts, final_project_backend/src/post/post.service.ts, final_project_backend/src/util/api-response.interface.ts, final_project_backend/src/util/response-util.ts, final_project_backend/src/util/user-info.decorator.ts
**기능 구현**
- 좋아요 / 좋아요 취소 기능 구현
- reponse-util 함수, apiReponse 인터페이스 구현 (추후 수정 예정)
- @userInfo custom decorator 생성
- jwtAuthGuard 파일 생성
**이 외 수정사항**
- cummunity - communityUser relation 연결
=> feat : 좋아요 기능 구현

final_project_backend/src/app.module.ts, final_project_backend/src/factory/notice-image-upload.factory.ts, final_project_backend/src/media/dto/create-media.dto.ts, final_project_backend/src/media/dto/update-media.dto.ts, final_project_backend/src/media/entities/media-file.entity.ts, final_project_backend/src/media/entities/media.entity.ts, final_project_backend/src/media/media.controller.ts, final_project_backend/src/media/media.module.ts, final_project_backend/src/media/media.service.ts, final_project_backend/src/notice/dto/create-notice.dto.ts, final_project_backend/src/notice/dto/update-notice.dto.ts, final_project_backend/src/notice/entities/notice-image.entity.ts, final_project_backend/src/notice/entities/notice.entity.ts, final_project_backend/src/notice/notice.controller.ts, final_project_backend/src/notice/notice.module.ts, final_project_backend/src/notice/notice.service.ts, final_project_backend/src/post/dto/create-post.dto.ts, final_project_backend/src/post/entities/post-image.entity.ts, final_project_backend/src/post/entities/post.entity.ts
=> 18 feature notice

final_project_backend/src/comment/comment.controller.ts, final_project_backend/src/comment/dto/create-comment.dto.ts
미디어 서버 구현 (일부..?) 완료
- 서버를 실행하면 미디어 서버도 같이 열림
- OBS에서 url, 스트림 키 입력 전 live post api에서 라이브 제목, 타입(가로버전 or 세로버전) 입력 후 스트림키를 받아옴
- obs studio > 설정 > 방송 > 다음 입력
- url: rtmp://localhost/live (배포시 rtmp://flant./live)
- stream key: api에서 받아온 스트림 키(유효기간 1분 안에 입력 후 방송 시작을 해야함)
=> [feature] #68 - feature media server

.github/workflows/cd.yml
=> [fix] ci/cd .env 수정

final_project_backend/src/live/live.service.ts
=> [fix] https 주석 제거

final_project_backend/src/live/live.service.ts
=> [fix] 디렉토리 수동 생성

final_project_backend/src/live/live.service.ts
=> Media server

final_project_backend/src/live/live.service.ts
=> [fix] 테스트 위해 console.log 추가

final_project_backend/src/live/live.service.ts
=> [fix] path.resolve > path.join으로 수정

final_project_backend/src/live/live.service.ts
=> [fix] console.log 추가

final_project_backend/src/live/live.service.ts
=> [fix] https 제외

final_project_backend/src/live/live.service.ts
=> [fix] try/catch 추가

final_project_backend/src/live/live.service.ts
=> [fix] s3 업로드 상대경로 수정

final_project_backend/src/live/live.service.ts
=> [fix] 방송 종료 시 s3에 업로드 수정

final_project_backend/src/live/live.service.ts
=> [fix] 방송 종료 로직 주석처리

final_project_backend/src/live/live.service.ts
=> [fix] config에 dash 추가

final_project_backend/src/live/live.service.ts
=> [fix] 디렉토리 변경

final_project_backend/src/live/live.service.ts, final_project_frontend/live.html
=> [fix] donepublish 콘솔

final_project_backend/src/live/live.service.ts
=> [fix] nodemediaserver start 위치변경

final_project_backend/src/live/live.service.ts
=> [fix] uploadtos3 함수 위치 이동

final_project_backend/src/live/live.service.ts
=> [fix] donePublish 수정

final_project_backend/package-lock.json, final_project_backend/package.json, final_project_backend/src/live/live.service.ts
=> [fix] 라이브서버 스트리밍 닫히는 로직 수정

final_project_backend/src/live/live.service.ts
=> [fix] ffmpeg 로그 출력

final_project_backend/src/live/live.service.ts
=> [fix] 방송종료 로직 추가

final_project_backend/src/live/live.service.ts
=> [fix] media 디렉토리 수정

final_project_backend/src/live/live.service.ts
=> [fix] s3 업로드 수정

final_project_backend/src/live/live.service.ts
=> [fix] 버킷 폴더 수정, 삭제 디렉토리 수정

final_project_frontend/package-lock.json, final_project_frontend/package.json
- 프론트엔드 package.json 충돌로 일어난 에러 해결
- package-lock.json 업데이트
=> fix : package.json 충돌 해결

final_project_backend/src/all-exceptions.filter.ts, final_project_backend/src/auth/auth.service.ts, final_project_frontend/src/services/api.ts, final_project_frontend/src/types/env.d.ts, final_project_frontend/tsconfig.json
프론트 문제 1번 포트 연결 문제 해결 2번문제 진행중
-  서버 .env 포트 연결 문제 있던거 정확하게 구분하고 나누어서 문제를 해결하였음
프론트 서버연결 확인됨
=> 프론트 문제 1번 포트 연결 문제 해결 2번문제 진행중

final_project_frontend/src/App.tsx, final_project_frontend/src/pages/LiveStreamingPage.tsx, final_project_frontend/src/services/api.ts, final_project_frontend/tsconfig.json
=> 라이브 스트리밍 넣은거

final_project_frontend/src/App.tsx, final_project_frontend/src/pages/LiveStreamingPage.tsx, final_project_frontend/src/services/api.ts
=> 74 feature frontend

final_project_backend/src/live/live.service.ts
=> [fix] https pem 파일 경로 추가

final_project_frontend/src/App.tsx, final_project_frontend/src/pages/MainPage.tsx, final_project_frontend/src/pages/board.tsx, final_project_frontend/src/services/api.ts
=> 커뮤니티 게시판 보드 문제 해결

final_project_backend/src/live/live.controller.ts, final_project_backend/src/live/live.service.ts, final_project_frontend/package-lock.json, final_project_frontend/package.json, final_project_frontend/src/pages/LiveStreamingPage.tsx
=> [refactor] 프론트 라이브 수정

final_project_frontend/src/pages/LiveStreamingPage.tsx
=> 라이브에 토큰인증 넣었음

final_project_backend/src/admin/entities/manager.entity.ts, final_project_backend/src/app.module.ts, final_project_backend/src/auth/auth.module.ts, final_project_backend/src/auth/auth.service.ts, final_project_backend/src/cart/cart.service.ts, final_project_backend/src/community/entities/community.entity.ts, final_project_backend/src/order/order.service.ts
=> [fix] 충돌수정

final_project_frontend/public/index.html, final_project_frontend/src/components/communityBoard/CommunityNavigationHeader.tsx, final_project_frontend/src/components/communityBoard/Header.tsx, final_project_frontend/src/styles/CommunityNavigationHeader.scss, final_project_frontend/src/styles/Header.scss
**구현 내용**
- 그룹명(community title) 위치 조정
- nav바 컨텐츠 중앙정렬 및 폰트 수정
- 헤더 알림 아이콘/드롭다운 메뉴 등 미구현 사항 주석처리
- 헤더 nav바 겹침 문제 해결
=> Fix : CommunityBoard Header/Nav바 UI 수정

final_project_frontend/src/pages/ArtistPostsBoard.tsx, final_project_frontend/src/pages/CommunityBoard.tsx, final_project_frontend/src/pages/MainPage.tsx, final_project_frontend/src/styles/CommunityList.scss
**구현 내용**
- 새로고침시 좋아요 상태 유지되지 않는 문제 해결
- MainPage Header 사용하지 않는 아이콘 삭제(알림)
**참고사항**
- 좋아요 로직의 경우 추후 리팩토링 예정
**<<<<< 아직 머지하지 말아주세요 >>>>>**
=> fix : 게시물 좋아요 후 새로고침 시 상태가 유지되지 않는 문제 해결

final_project_frontend/src/components/communityBoard/PostForm.scss, final_project_frontend/src/components/communityBoard/PostForm.tsx, final_project_frontend/src/pages/media/media.scss, final_project_frontend/src/pages/media/media.tsx
#166 
미디어 기능 조정
유튜브 URL 혹은 .mp4 파일만 현재 재생 가능합니다
이미지 확장자는 .jpg .jpeg .png만 업로드 허용하고 있습니다
postForm 기능
글쓰기 버튼 이미지 업로드와 업로드 대기중인 파일명 표기하도록 수정되었습니다.
=> fix/media, postForm

final_project_frontend/src/components/communityBoard/PostCard.tsx, final_project_frontend/src/styles/PostCard.scss
**구현 내용**
- 여백 색 지정 #fafafa
- 사진 여러개 입력시 틀에 맞게 조절
=> feat : PostCard 이미지 여러 개 입력 시 크기 조절 및 여백 처리

final_project_frontend/src/App.tsx, final_project_frontend/src/components/Layout.tsx, final_project_frontend/src/components/communityBoard/CommunityNavigationHeader.tsx, final_project_frontend/src/components/communityBoard/PostForm.tsx, final_project_frontend/src/pages/LoginPage.tsx, final_project_frontend/src/pages/MainPage.tsx, final_project_frontend/src/pages/UserInfo.tsx, final_project_frontend/src/pages/media/media.tsx, final_project_frontend/src/pages/merchandiseDetail.tsx
- 사용하지 않는 코드 삭제
- console.log() 제거
- 소켓 에러로 인한 채팅 기능 임시 제거
=> fix : socket.io 에러로 인한 ChatComponent 주석처리

final_project_frontend/src/components/communityBoard/Header.tsx, final_project_frontend/src/pages/MainPage.tsx, final_project_frontend/src/pages/media/media.scss, final_project_frontend/src/pages/merchandiseDetail.tsx, final_project_frontend/src/services/api.ts
- 모달창에 장바구니 추가
- 상품 상세조회에 장바구니로 이동 버튼 추가
- 미디어 조회 디자인 수정
- 결제 기능 프론트 오류 수정
=> 177 feature 미디어 & 장바구니 수정

final_project_frontend/src/pages/merchandiseDetail.scss
=> 177 상품 상세사진 배치 수정

final_project_backend/src/app.module.ts, final_project_backend/src/main.ts, final_project_frontend/package-lock.json, final_project_frontend/package.json, final_project_frontend/src/components/ChatComponent.tsx, final_project_frontend/src/context/ChatContext.tsx, final_project_frontend/src/pages/board.scss
채팅수정 진행중이던거  + 사이드바 글자 크기 조절 및 배치 정렬
-
=> 채팅수정 진행중이던거  + 사이드바 글자 크기 조절 및 배치 정렬

final_project_frontend/src/pages/board.scss
=> 닉네임 삭제된거 수정후 글자 조절
